### ISSUE TITLE
BSOD 

### ISSUE THREAD

**Issue by sternlicht** [pyxll/pyxll-jupyter#1]
Clicking the Jupyter, qt or tk plug-in within the pyxll Excel tab results in a BSOD with the following error:

stop code: APC_INDEX_MISMATCH
what failed: win32kfull.sys

System
Winver: 2004
Excel: 64-bit
Python version: 3.8.5

**Comment by tonyroberts** [comment]
This looks like a driver issue since this is win32kfull.sys is a kernel mode module.

Help has been offered via PyXLL support, along with some Qt code to test to see if the same problem exists when running in plain Python.

I'm closing this for now since this doesn't appear to be a problem with this project, but we can re-open later if needed
